---

application_user: vagrant

# application paths
application_root: /opt/sitterfied-api

# virtualenv paths
application_virtualenv_root: /opt/envs/sitterfied-api
application_virtualenv_bin: /opt/envs/sitterfied-api/bin
